import { useEffect, useState } from 'react'
import { ArrowUpRight, BarChart3, Check, ChevronDown, Circle, ExternalLink, Mail, Menu, Moon, Phone, Sun, X } from 'lucide-react'
import { portfolio } from './data/portfolio'

const navItems = [['About', 'about'], ['Skills', 'skills'], ['Experience', 'experience'], ['Education', 'education'], ['Projects', 'projects'], ['Contact', 'contact']]
const projectFields = ['Project Name', 'Description', 'Problem', 'Solution', 'Technologies', 'Skills Used', 'GitHub', 'Live Demo', 'Screenshots']

function App() {
  const [dark, setDark] = useState(() => localStorage.getItem('theme') === 'dark')
  const [menuOpen, setMenuOpen] = useState(false)
  const [sent, setSent] = useState(false)
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; localStorage.setItem('theme', dark ? 'dark' : 'light') }, [dark])
  const closeMenu = () => setMenuOpen(false)
  return <div className="site-shell">
    <header className="navbar">
      <a className="brand" href="#home" onClick={closeMenu}><span className="brand-mark">MR</span><span>Mohamed Ramy<br /><small>Hanafy</small></span></a>
      <button className="menu-toggle" aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>
      <nav className={menuOpen ? 'nav-links open' : 'nav-links'}>{navItems.map(([label, id]) => <a key={id} href={`#${id}`} onClick={closeMenu}>{label}</a>)}<a className="nav-cta" href="#contact" onClick={closeMenu}>Let's connect <ArrowUpRight size={15} /></a><button className="theme-toggle" aria-label="Toggle color theme" onClick={() => setDark(!dark)}>{dark ? <Sun size={17} /> : <Moon size={17} />}</button></nav>
    </header>

    <main>
      <section className="hero section-grid" id="home"><div className="hero-copy reveal"><p className="eyebrow"><span className="status-dot" /> Open to future opportunities</p><h1>Finance, with a<br /><em>clearer view.</em></h1><p className="hero-lede">Building a strong foundation in finance, financial analysis, accounting, and data-driven decision making.</p><div className="hero-actions"><a className="button primary" href="#experience">View my experience <ArrowUpRight size={17} /></a><a className="button text-button" href="#contact">Contact me <ArrowUpRight size={17} /></a><a className="button text-button" href="#credentials">Download CV <ArrowUpRight size={17} /></a></div><div className="hero-meta"><span>Based in {portfolio.location}</span><span>AAST · Class of 2029</span></div></div>
        <div className="hero-visual reveal">
            <img src="/profile.jpg" alt="Mohamed Ramy Hanafy" />
        </div>
        </section>

      <section className="intro-band"><div className="section-kicker">01 / Profile</div><p>{portfolio.profile}</p><a href="#about" className="circle-link" aria-label="Read more about Mohamed"><ArrowUpRight /></a></section>

      <section className="section two-col" id="about"><div><p className="section-kicker">02 / About me</p><h2>Curious about the<br /><em>numbers behind</em><br />the story.</h2></div><div className="section-body"><p>I am a second-year Business Administration and Technology student specializing in Accounting and Finance at AAST. I have a strong interest in financial analysis, financial reporting, accounting principles, and data-driven decision making.</p><p>During my CIB summer internship, I gained practical exposure to banking operations, financial analysis, reporting, account reconciliation, compliance procedures, and risk management.</p><p>I enjoy analytical problem-solving and continuously work on improving my technical and professional skills. My goal is to build a successful career in finance and become a strong financial analyst.</p><a href="#contact" className="underlined-link">Let's connect <ArrowUpRight size={16} /></a></div></section>

      <section className="section profile-strip"><div><p className="section-kicker">03 / Quick profile</p><h2>The essentials,<br /><em>at a glance.</em></h2></div><div className="profile-grid">{[['Name', portfolio.name], ['Location', portfolio.location], ['University', 'AAST'], ['Study', 'Accounting & Finance'], ['Academic level', 'Second Year'], ['Languages', 'Arabic - Native / English - Excellent'], ['Career interest', 'Financial Analysis / Finance / Banking / Data Analysis'], ['Contact', portfolio.email], ['GitHub', portfolio.github]].map(([key, value]) => <div className="profile-item" key={key}><span>{key}</span><strong>{value}</strong></div>)}</div></section>

      <section className="section skills-section" id="skills"><div className="section-heading"><div><p className="section-kicker">04 / Capabilities</p><h2>Skills that turn<br /><em>data into direction.</em></h2></div><p>Built through coursework, practical exposure, and a habit of looking closer.</p></div><div className="skills-grid">{Object.entries(portfolio.skills).map(([category, skills]) => <div className="skill-group" key={category}><div className="skill-title"><BarChart3 size={18} /><span>{category}</span></div><div className="badges">{skills.map(skill => <span className="badge" key={skill}>{skill}</span>)}</div></div>)}</div></section>

      <section className="section experience-section" id="experience"><div className="section-heading"><div><p className="section-kicker">05 / Experience</p><h2>Learning how<br /><em>finance moves.</em></h2></div><span className="date-label">JUN 2025 — JUL 2025</span></div><article className="experience-card"><div className="experience-marker"><Circle size={18} fill="currentColor" /></div><div className="experience-main"><p className="eyebrow">CIB Summer Internship</p><h3>Financial Analysis & Banking Operations</h3><p className="muted">CIB · Cairo, Egypt</p><div className="experience-columns"><p>Analysed financial and operational data to support business decisions. Assisted in preparing reports and reviewing banking transactions, with exposure to financial reporting, account reconciliation, compliance procedures, and risk management.</p><ul>{['Developed advanced Excel skills for data analysis and reporting.', 'Worked collaboratively with banking professionals in a fast-paced environment.', 'Improved analytical, problem-solving, and communication skills.'].map(item => <li key={item}><Check size={15} />{item}</li>)}</ul></div></div></article></section>

      <section className="section education-section" id="education"><div><p className="section-kicker">06 / Education</p><h2>Grounded in<br /><em>the fundamentals.</em></h2></div><div className="education-card"><span className="year">2025 — PRESENT</span><h3>Arab Academy for Science,<br />Technology & Maritime Transport</h3><p>Business Administration and Technology<br /><strong>Accounting and Finance</strong></p><div className="education-footer"><span>Academic level</span><strong>Second Year</strong></div></div></section>

      <section className="section projects-section" id="projects"><div className="section-heading"><div><p className="section-kicker">07 / Selected projects</p><h2>A portfolio<br /><em>in progress.</em></h2></div><p>My project portfolio is currently being developed. New academic and data-analysis projects will be added here as they are completed.</p></div><div className="project-grid">{[1, 2, 3].map(number => <article className="project-placeholder" key={number}><span className="placeholder-index">0{number}</span><div><p className="eyebrow">Placeholder</p><h3>[ADD PROJECT {number}]</h3><p>Reserved for a confirmed academic or data-analysis project.</p><span className="placeholder-line">Project details to come <ArrowUpRight size={15} /></span></div></article>)}</div><div className="future-categories"><span>Future portfolio categories</span>{['Financial Analysis', 'Excel Dashboards', 'Data Analysis', 'Accounting Projects', 'Banking Analysis', 'Business Analysis', 'Supply Chain Analysis', 'Power BI Projects'].map(item => <span className="category-pill" key={item}>{item}</span>)}</div></section>

      <section className="section interests-section"><div><p className="section-kicker">08 / Areas of interest</p><h2>Where I’m<br /><em>looking next.</em></h2></div><div className="interest-list">{portfolio.interests.map((interest, index) => <div key={interest}><span>0{index + 1}</span><strong>{interest}</strong><ArrowUpRight size={18} /></div>)}</div></section>

      <section className="section credentials-section" id="credentials"><div><p className="section-kicker">09 / Credentials</p><h2>Still being<br /><em>earned.</em></h2></div><div className="empty-state"><span className="empty-icon"><ChevronDown /></span><h3>Certifications and achievements will be added here as they are earned.</h3><p>[ADD CERTIFICATIONS]</p><p>[ADD ACHIEVEMENTS]</p><p>[ADD CV FILE]</p></div></section>

      <section className="contact-section" id="contact"><div className="contact-inner"><div className="contact-copy"><p className="section-kicker">10 / Contact</p><h2>Let's build a<br /><em>conversation.</em></h2><p>I am always interested in connecting with professionals, recruiters, and organizations in the fields of finance, accounting, banking, and data analysis.</p><div className="contact-links"><a href={`mailto:${portfolio.email}`}><Mail size={17} />{portfolio.email}</a><a href={`tel:${portfolio.phone}`}><Phone size={17} />{portfolio.phone}</a><a href={portfolio.linkedin} target="_blank" rel="noreferrer"><ExternalLink size={17} />Connect on LinkedIn <ExternalLink size={13} /></a></div></div><form className="contact-form" onSubmit={e => { e.preventDefault(); setSent(true) }}><label>Name<input required name="name" placeholder="Your name" /></label><label>Email<input required type="email" name="email" placeholder="you@example.com" /></label><label>Subject<input required name="subject" placeholder="How can we connect?" /></label><label>Message<textarea required name="message" rows={4} placeholder="A little about your message..." /></label><button className="button light-button" type="submit">{sent ? 'Message ready to send' : 'Send message'} {sent ? <Check size={17} /> : <ArrowUpRight size={17} />}</button><small>Form UI is ready. Connect Formspree, EmailJS, Resend, or another backend in the submit handler before deployment.</small></form></div></section>
    </main>
    <footer className="footer"><div className="footer-top"><a className="brand" href="#home"><span className="brand-mark">MR</span><span>Mohamed Ramy<br /><small>Hanafy</small></span></a><p>Accounting & Finance Student<br />Aspiring Financial Analyst</p><div><a href={`mailto:${portfolio.email}`}>{portfolio.email}</a><br /><a href={portfolio.linkedin} target="_blank" rel="noreferrer">LinkedIn <ExternalLink size={12} /></a></div></div><div className="footer-bottom"><span>© 2026 Mohamed Ramy Hanafy. All rights reserved.</span><a href="#home">Back to top <ArrowUpRight size={14} /></a></div></footer>
  </div>
}

export default App
